## The Tensorflow Trials

For much of the past week, you've been using tensors with your Deep Learning models. Over the course of today's challenges, you'll be manipulating tensors extensively and working with some unconventional model architectures. 


In this warm up, you'll be introduced to some new methods. 

All the methods here are going to make tackling challenges later in the day 100x easier, so if you do get stuck later on, make sure you come back here to see how you achieved the right answers. 

In [1]:
import tensorflow as tf

2025-05-23 11:32:03.910317: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-23 11:32:04.063771: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-23 11:32:04.199867: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1747992724.313590    1082 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1747992724.349639    1082 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1747992724.619167    1082 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linkin

A) Use `tf.ones` to create a tensor `a` filled with ones of shape (3,3).

In [2]:
a = tf.ones(shape=(3, 3))
print(a)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


E0000 00:00:1747992844.900380    1082 cuda_executor.cc:1228] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.
W0000 00:00:1747992844.900998    1082 gpu_device.cc:2341] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


B) Use tf.expand_dims to make `a` an object of shape (1,3,3) called `b`.

In [4]:
b = tf.expand_dims(a, axis=0)  # Adds a new dimension at the front

print(b.shape)  # Should print: (1, 3, 3)
print(b)


(1, 3, 3)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 3, 3), dtype=float32)


C) Create a tensor `c` filled with zeroes of size (9,1)

In [7]:
c = tf.zeros(shape=(9, 1), dtype = 'int32')
print(c)

tf.Tensor(
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]], shape=(9, 1), dtype=int32)


D) Reshape `c` to be of shape (1, 3, 3). Name it `d`.

In [9]:
d = tf.reshape(c, shape=(1,3,3))  # Adds a new dimension at the front

print(d.shape)  # Should print: (1, 3, 3)
print(d)

(1, 3, 3)
tf.Tensor(
[[[0 0 0]
  [0 0 0]
  [0 0 0]]], shape=(1, 3, 3), dtype=int32)


E) Use `tf.matmul` to matrix multiply `b` and `d` with each other and now assign the tensor to `e`. 

In [12]:


e = tf.matmul(b, d)  # shape (1, 3, 3)
print(e)


tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 3, 3), dtype=float32)


F) Below is a `numpy` array. Convert it to a tensor named `array_tensor`. Then use `tf.cast` to ensure it is of dtype `float` not `int`. Assign the result to `f`.

In [24]:
import numpy as np

In [25]:
array = np.array([[
    [1,2,3],
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])

In [31]:
array_tensor = tf.convert_to_tensor(array)
f = tf.cast(array_tensor, dtype = tf.float32)
f

<tf.Tensor: shape=(1, 4, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]], dtype=float32)>

G) Select the values in the __last column__ of `f` and save this to `g`. To be clear, `g` should have shape (4,) and contain the values `3,3,6,9`. 

In [39]:
g = f[0,:,2]
g


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([3., 3., 6., 9.], dtype=float32)>

H) Expand the dimensions of g so that it's of shape (4,1). Assign this to `h`.

In [41]:
h = tf.expand_dims(g, axis=1)
h

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[3.],
       [3.],
       [6.],
       [9.]], dtype=float32)>

I) Multiply e with f, using `tf.matmul` with the optional `transpose_b` argument (`e` must come first in your positional arguments, then `f`). Assign this to `i`.

In [43]:
i = tf.matmul(e, f, transpose_b=True)
print(i.shape)  # Expected: (1, 3, 4)
print(i)

(1, 3, 4)
tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(1, 3, 4), dtype=float32)


J) Create a `(10,10)` tensor filled with ones. Then use `tf.linalg.band_part()` to mask out the upper triangle of the matrix (i.e. the upper triangle should all be 0s). Assign to `j`.

In [47]:
# Create a 10x10 tensor of ones
ones_matrix = tf.ones((10, 10))

# Mask out the upper triangle by keeping only the lower triangle and diagonal
# tf.linalg.band_part(input, num_lower, num_upper)
# Setting num_upper=0 keeps zeroes above the diagonal
j = tf.linalg.band_part(ones_matrix, num_lower=-1, num_upper=0)

print(j)


tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(10, 10), dtype=float32)


K) Take the `number_list` below and make it a tensor. Assign it to `k`.

In [49]:
number_list = [1, 2, 3, 4, 8]
k = tf.convert_to_tensor(number_list)

print(k)
print(k.shape)  # Should be (5,)


tf.Tensor([1 2 3 4 8], shape=(5,), dtype=int32)
(5,)


L) Use `tf.expand_dims` to make `k` into a tensor of shape (1,5). Assign to `l`.

In [51]:
l = tf.expand_dims(k,axis=0)
l

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[1, 2, 3, 4, 8]], dtype=int32)>

M) Use `tf.tile` to repeat `l` (read as "L") 50 times, with an eventual shape of `(50, 5)`. Assign to `m`.

In [53]:
# Tile l 50 times along axis 0 (rows)
m = tf.tile(l, multiples=[50, 1])  # shape (50, 5)

print(m.shape)  # (50, 5)



(50, 5)


N) Use a simple Boolean statement to create a tensor containing `True` values for where `m` is 3  and `False` for where it is not 3. Assign to `n`

In [55]:
n = tf.equal(m, 3)


O) Divide every value in you variable `m` by 3. Assign to `o`.

In [58]:
o = m / 3



P) Use `tf.concat()` to take the list of two tensors below of shape (5,5) and (5,5) each and turn them into a final tensor of shape (10,5). Assign to `p`. Think carefully about the concation axis.

In [60]:
tensor_list = [tf.ones((5,5)), tf.ones((5,5))]
tensor_list

[<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32)>]

In [61]:

p = tf.concat(tensor_list, axis=0)  # Concatenate along rows

print(p.shape)  # Should print (10, 5)
print(p)


(10, 5)
tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(10, 5), dtype=float32)


### Check your answers

In [62]:
from nbresult import ChallengeResult

result = ChallengeResult('tensors',
                            a = a,
                            b = b,
                            c = c,
                            d_shape = d.shape,
                            e = e,
                            f = f,
                            g = g,
                            h = h,
                            i = i,
                            j = j,
                            k = k,
                            l = l,
                            m = m,
                            n = n,
                            o = o,
                            p_shape = p.shape
)

result.write()
print(result.check())


============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/saranjthilak92/.pyenv/versions/3.12.9/envs/lewagon/bin/python
cachedir: .pytest_cache
Fugue tests will be initialized with options:
rootdir: /home/saranjthilak92/code/saranjthilak/06-Deep-Learning/05-Transformers/data-tensor-trials/tests
plugins: fugue-0.9.1, typeguard-4.4.2, anyio-4.8.0
collecting ... collected 15 items

test_tensors.py::TestTensors::test_a PASSED                              [  6%]
test_tensors.py::TestTensors::test_b PASSED                              [ 13%]
test_tensors.py::TestTensors::test_c PASSED                              [ 20%]
test_tensors.py::TestTensors::test_d_shape PASSED                        [ 26%]
test_tensors.py::TestTensors::test_e PASSED                              [ 33%]
test_tensors.py::TestTensors::test_f PASSED                              [ 40%]
test_tensors.py::TestTensors::test_g PASSED  

### Great work 🔥

Now it's time to get stuck into some modelling!